spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:docker-profile}

  datasource:
    url: jdbc:mysql://${DATABASE_HOST:online-bookstore-db}:3306/${DATABASE_NAME:ONLINE_BOOKSTORE}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:OnlineBookDb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8082

springdoc:
  show-actuator: false
  use-management-port: false
  api-docs:
    path: /arp/api-docs
  swagger-ui:
    path: /arp/swagger-ui.html
    tagsSorter: alpha
    operationsSorter: alpha
    enabled: true
    csrf:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"